config/routes.rb
Rails.application.routes.draw do
  get 'users/home', to:"users#home"
  post '/ajax/new_block', to: "service_providers/schedules#ajax_new_block"
  post '/ajax/block_resize', to: "service_providers/schedules#ajax_block_resize"
  post '/ajax/schedule', to: "service_providers/schedules#ajax_schedules"
  post '/ajax/service_provider_stats', to:"service_providers/jobs#ajax_stats"
  post '/ajax/resquest/maid', to:"welcome#number_of_maids"

  post '/ajax/perish', to: "services#request_perish"
  post '/ajax/search_maid', to:"services#ajax_search_maid"

  get 'service_providers/schedules/:id' => 'service_providers/schedules#show'
  get 'service_providers/jobs' => 'service_providers/jobs#show'
  get 'service_providers/accept_job' => 'service_providers/jobs#accept_job'
  get 'service_providers/reject_job' => 'service_providers/jobs#reject_job'
  get 'service_providers/profile' => 'service_providers#profile'

  get 'help/client', to:"help#help_client"
  get 'help/user', to:"help#help_user"

  get "services/search_service_provider" => 'services#search_service_provider'
  post "services/request_service" => "services#request_service"
  post "/services/request_service_submit" =>"services#request_service_submit"
  get "/services/profile/:id" => "services#profile"
  get 'services/rating', to:"services#rating"
  get 'services/feedback', to:"services#feedback"
  post "/services/rate" => "rankings#create"
  post "/services/feedback" => "feedbacks#create"
  get 'users/profile' => 'users#profile'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'welcome#index'
    devise_for :users, :controllers => {:registrations => "registrations"}
    devise_scope :user do
      get "users/new_user" => 'registrations#new_user'
      get "users/new_client" => 'registrations#new_client'
      post "users/create_client" => "registrations#create_client"
      post "users/create_user" => "registrations#create_user"
      get "users/publicprofile" => 'users#publicprofile'

    end
    resources :guestbooks, :answer_types, :answers, :additional_informations, :states, :histories, :rankings, :services, :feedbacks, :payment_types, :premia, :service_provider_premia, :days, :slots, :schedules, :service_types, :service_type_service_providers, :service_providers, :addresses
    get '*path', to: redirect { |params, request| "/#{params[:locale]}" }
  end
  get '/*locale*/*path/assets', to: redirect("")
  get '/*locale/*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '/*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.locale}")
end

app/models/service_provider.rb
class ServiceProvider < ActiveRecord::Base
  belongs_to :user
  has_many :service_type_service_provider
  has_many :additional_information
  has_many :service_provider_premium
  has_many :service
  has_many :schedule
  has_many :time_table
  has_many :feedback


  def add_slot(date_start, date_end)
    slots = TimeTable.where(service_provider_id: self.id,
                            start_time: date_start,
                            end_time: date_end)

    if slots.empty?
      slots = TimeTable.new(service_provider_id: self.id,
                            start_time: date_start,
                            end_time: date_end)
      slots.save!
    end

  end
  
  def update_slot(id, time_start, time_end)
    puts time_start
    puts time_end
    slot = TimeTable.find(id)
    slot.update(start_time: time_start)
    slot.update(end_time: time_end)
    #slot.update_attributes(stax rt_time: time_start, end_time: time_end)
    
  end  

  def add_schedule(slot,day)

  	schedules = Schedule.where(service_provider_id: self.id, day_id: day.id)
  	#Se o cliente ainda nao tem slots naquele dia pode-se adicionar a vontade
  	if schedules.empty?
  		schedule = Schedule.new(service_provider_id: self.id, 
  														slot_id: slot.id, 
  														day_id: day.id, 
  														availability: true)
  		schedule.save!
  	else
  		#Mas se tem temos que ter cuidado e verificar se e um slot novo ou 
  		#apenas esta a mudar o horario de um
  		puts "ola"
  		puts schedules.inspect
  		#Ir buscar os slots desse dia e verificar se é um novo ou uma alteracao


  	end
  end


  
end

app/controllers/service_providers/jobs_controller.rb
class ServiceProviders::JobsController < ApplicationController


	def show
		@active_jobs = true
		@sidebar = true
		@navbar = true
		srvp = ServiceProvider.where(user_id: current_user.id).first
		@pending_jobs = get_pending_jobs(srvp)
		@accepted_jobs = get_accepted_jobs(srvp)
		@comp_rec_jobs = get_completed_rejected_jobs(srvp)
	end

	def ajax_stats
		srvp = ServiceProvider.where(user_id: current_user.id).first
		services_eng = Service.where(service_provider_id: srvp.id,
																 service_type_id: 1,
																 state: 3).count

		services_limp = Service.where(service_provider_id: srvp.id,
																 service_type_id: 2,
																 state: 3).count

		services_ref = Service.where(service_provider_id: srvp.id,
																 service_type_id: 3,
																 state: 3).count
		services_comp = Service.where(service_provider_id: srvp.id,
																 service_type_id: 4,
																 state: 3).count
		render :json => {:eng => services_eng,
										 :limp => services_limp,
										 :ref => services_ref,
										 :comp => services_comp}
	end




	def accept_job
		puts params.inspect
		params.permit!
		service = Service.find(params[:id])
		service.state = 2
		service.save!

		redirect_to :back
	end

	def reject_job
		params.permit!
		service = Service.find(params[:id])
		service.state = 4
		service.save!
		redirect_to :back
	end

	private
		def get_pending_jobs(srvp)
			services = Service.where(service_provider_id: srvp.id,  state: 1).order(service_date: :asc)
			pending_jobs = []
			services.each{ |elem| pending_jobs << create_service_hash(elem)}
			return pending_jobs
		end

		def get_accepted_jobs(srvp)
			services = Service.where(service_provider_id: srvp.id,  state: 2).order(service_date: :asc)
			accepted_jobs = []
			services.each{ |elem| accepted_jobs << create_service_hash(elem)}
			return accepted_jobs
		end

		def get_completed_rejected_jobs(srvp)
			services = Service.where(service_provider_id: srvp.id,  state: [3,4]).order(service_date: :asc)
			accepted_jobs = []
			services.each{ |elem| accepted_jobs << create_comp_rej_hash(elem)}
			return accepted_jobs
		end


		def create_service_hash(service)	
			user = User.find(service.user_id)
			hash = { :id => service.id, 
							 :type => service.service_type_id, 
							 :number_of_rooms => service.number_of_rooms,
							 :district => service.district,
							 :zip_code => service.zip_code,
							 :street => service.street,
							 :door_number => service.door_number,
							 :city => service.city,
							 :date => service.service_date,
							 :service_start => service.service_start,
							 :service_end => service.service_end,
							 :additional_information => service.additional_information,
							 :user => {:name => user.name, :photo => user.photo}}
			return hash
		end

		def create_comp_rej_hash(service)	
			user = User.find(service.user_id)
			hash = { :type => service.service_type_id, 
							 :date => service.service_date,
							 :state => service.state,
							 :user => user.name}
			return hash
		end


end

app/controllers/service_providers/schedules_controller.rb
class ServiceProviders::SchedulesController < ApplicationController
  before_action only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @schedules = Schedule.all
    respond_with(@schedules)
  end

  def show
    @active_schedule = true
    @sidebar = true
    @navbar = true
  end

  def new
    @schedule = Schedule.new
    respond_with(@schedule)
  end

  def edit
  end

  def ajax_schedules
    srvp = ServiceProvider.where(user_id: current_user.id).first
    res = TimeTable.where(service_provider_id: srvp.id)

    jres = {}

    res.each { |elem| jres[elem.id] = { "start_time" => up_date(elem.start_time), 
                                        "end_time" => up_date(elem.end_time)}}

    render :json => jres
  end

  def ajax_block_resize
    params.permit!

    date_start = DateTime.parse(params[:start])
    date_end = DateTime.parse(params[:end])


    srvp = ServiceProvider.where(user_id: current_user.id).first
    srvp.update_slot(params[:id], date_start, date_end)
    render :json => {:result => "ok"}
  end

  def ajax_new_block
    params.permit!

    date_start = DateTime.parse(params[:time_start])
    date_end = DateTime.parse(params[:time_end])

    #slot = slot_exists(date_start.to_time, date_end.to_time)
    #day = day_exists(date_start.wday)
    srvp = ServiceProvider.where(user_id: current_user.id).first

    srvp.add_slot(date_start, date_end)
    #srvp.add_schedule(slot,day)
    
    render :json =>{:result  => "ok"}
  end
  def create
    @schedule = Schedule.new(schedule_params)
    @schedule.save
    respond_with(@schedule)
  end


  def update
    @schedule.update(schedule_params)
    respond_with(@schedule)
  end

  def destroy
    @schedule.destroy
    respond_with(@schedule)
  end

  private

    def up_date(odate)
        #cdate = next_wday(odate)
        #return odate.change(:day => cdate.day)
        tdate = Date.today
        cdate = tdate.monday
        #A semana comeca a segunda no rails
        #Se a data for um domingo entao pedo o domingo anterior a segunda da semana actual
        #caso contrario calcula o dia corresponde ao dia da semana da  data antiga
        if odate.wday == 0 
          cdate = cdate.yesterday
        else
          cdate = cdate.change(:day => cdate.day + odate.wday-1)
        end
        return odate.change(:day => cdate.day, 
                            :month => cdate.month, 
                            :year => cdate.year)
    end 

    #verifys if the days is already in the db
    # if it does it return the existing one otherwise return a new one.
    def day_exists(number)
      day = Day.new
      day.description = day.day_name(number)

      if day.exists?
        days = Day.where(description: day.description)
        day = Day.new(days.first.attributes)
      else
        day.save!  
      end  
      return day
    end
    #verifys if a slot with that time already exists
    # if it does it return the existing one otherwise return a new one.
    def slot_exists(date_start, date_end)

      if Slot.time_exist(date_start, date_end)

        slots = Slot.where(begining_hour: date_start, ending_hour: date_end)
        slot = Slot.new(slots.first.attributes)
      
      else
        
        slot = Slot.new(begining_hour: date_start, ending_hour: date_end)
        slot.save!
      
      end

      return slot
    end

    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    def schedule_params
      params[:schedule]
    end
end

app/controllers/service_providers_controller.rb
class ServiceProvidersController < ApplicationController
  before_action :set_service_provider, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @service_providers = ServiceProvider.all
    respond_with(@service_providers)
  end

  def show
    respond_with(@service_provider)
  end

  def new
    @service_provider = ServiceProvider.new
    respond_with(@service_provider)
  end

  def edit
  end

  def create
    @service_provider = ServiceProvider.new(service_provider_params)
    @service_provider.save
    respond_with(@service_provider)
  end

  def profile
    @active_profile =true
    @sidebar = true
    @navbar = true
    @user = ServiceProvider.find(current_user.id)
    @services = Service.where(service_provider_id: current_user.id)
  end

  def update
    @service_provider.update(service_provider_params)
    respond_with(@service_provider)
  end

  def destroy
    @service_provider.destroy
    respond_with(@service_provider)
  end

  private
    def set_service_provider
      @service_provider = ServiceProvider.find(params[:id])
    end

    def service_provider_params
      params[:service_provider]
    end
end

app/helpers/service_providers_helper.rb
module ServiceProvidersHelper
end

app/views/service_providers/_form.html.erb
<%= simple_form_for(@service_provider) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/service_providers/edit.html.erb
<h1>Editing service_provider</h1>
<%= render 'form' %>
<%= link_to 'Show', @service_provider %> |
<%= link_to 'Back', service_providers_path %>

app/views/service_providers/index.html.erb
<h1>Listing service_providers</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @service_providers.each do |service_provider| %>
      <tr>
        <td><%= link_to 'Show', service_provider %></td>
        <td><%= link_to 'Edit', edit_service_provider_path(service_provider) %></td>
        <td><%= link_to 'Destroy', service_provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Service provider', new_service_provider_path %>

app/views/service_providers/new.html.erb
<h1>New service_provider</h1>

<%= render 'form' %>

<%= link_to 'Back', service_providers_path %>

app/views/service_providers/profile.html.erb
<div class="content">
	<div class="panel panel-inverse">
	    <div class="panel-heading">
	        <div class="panel-heading-btn">
	            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand" data-original-title="" title=""><i class="fa fa-expand"></i></a>
	            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
	            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
	            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove" data-original-title="" title=""><i class="fa fa-times"></i></a>
	        </div>
	        <h4 class="panel-title">O seu perfil</h4>
	    </div>
	    <div class="panel-body">
			<div class="media media-lg">
				<a class="pull-left" href="javascript:;">
				<a class="pull-left" href="javascript:;">
					<%= image_tag current_user.photo, class: "media-object" %>
				</a>
					<!-- <img src="assets/img/gallery/gallery-1.jpg" alt="" class="media-object"> -->
				</a>
				<div class="media-body">
					<div class="media-body">
					<h4 class="media-heading"><%= current_user.name%></h4>
					<p><%= current_user.description%></p>
					<p><b>Email:</b> <%= current_user.email%></p>
					<p><b>Telefone:</b> <%= current_user.phone%></p>
					<p><b>Telemóvel:</b> <%= current_user.cell_phone%></p>
					<p><b>Data de Nascimento</b> <%= current_user.birth_date%></p>
					<p><b>Nacionalidade: </b> <%= current_user.nationality%></p>
					<p><b>Sexo:</b> <% if current_user.gender %>
						Masculino
						<%else%>
						Feminino
						<%end%></p>
					<p><b>Informação: </b>: <%= current_user.bio%></p>
				</div>
				</div>
			</div>
		</div>
	</div>
</div>


<div id="content" class="content">
			<!-- begin breadcrumb -->
			<!-- end breadcrumb -->
			<!-- begin page-header -->
			<!-- end page-header -->
			<!-- begin timeline -->
			<ul class="timeline">
				<% @services.order(:service_start).each do |s|%>
			    <li>
			        <!-- begin timeline-time -->
			        <div class="timeline-time">
			            <span class="date"><%= s.service_date%></span>
			            <span class="time"><%= s.service_start.strftime("%H:%M")%></span>
			        </div>
			        <!-- end timeline-time -->
			        <!-- begin timeline-icon -->
			        <div class="timeline-icon">
			            <a href="javascript:;"><i class="fa fa-home"></i></a>
			        </div>
			        <!-- end timeline-icon -->
			        <!-- begin timeline-body -->
			        <div class="timeline-body">
			            <div class="timeline-header">
			                <span class="userimage"><%= image_tag s.service_provider.user.photo%></span>
			                <span class="username"><a href="javascript:;"><%= s.service_provider.user.name%></a> <small></small></span>
			            </div>
			            <div class="timeline-content">
                            <p>
                                <strong>Cód. Postal:</strong>
			                      <%= s.zip_code %>
			                      <br/>
			                      <strong>Cidade:</strong>
			                      <%= s.city %>
			                      <br/>
			                      <strong>Rua:</strong>
			                      <%= s.street %>
			                      <br/>
			                      <strong>Info. Adicional:</strong>
			                      <%= s.additional_information %>
                            </p>
			            </div>
			            <div class="timeline-footer">
			            	<% if not s.ranking %>
			            		<a href="/services/rating" class="m-r-15"><i class="fa fa-thumbs-up fa-fw"></i> Avaliar</a>
			            	<% else %>
			            		<% (1..s.ranking.value).each do |v| %>
			            			<i class="fa fa-2x fa-star"></i>
			            		<% end %>
			            	<% end %>
			            </div>
			        </div>
			        <!-- end timeline-body -->
			    </li>
			  <%end%>
			</ul>
			<!-- end timeline -->
		</div>

app/views/service_providers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_service_provider_path(@service_provider) %> |
<%= link_to 'Back', service_providers_path %>